# Development Environment Secrets
# Note: These are example values for development only
# In production, use proper secret management systems

secrets:
  - name: gemini-api-key
    type: generic
    data:
      api-key: "AIzaSyB07cgUDp4zUUzbbE24Ounj3VA59obDMEw-dev"
    encrypted: false

  - name: redis-password
    type: generic
    data:
      password: "dev-redis-password-123"
    encrypted: false

  - name: mcp-service-tokens
    type: generic
    data:
      user-service-token: "dev-user-service-token-123"
      transaction-service-token: "dev-transaction-service-token-456"
      product-service-token: "dev-product-service-token-789"
      order-service-token: "dev-order-service-token-012"
    encrypted: false

  - name: a2a-encryption-keys
    type: generic
    data:
      encryption-key: "dev-a2a-encryption-key-32-chars-long"
      signing-key: "dev-a2a-signing-key-32-chars-long"
    encrypted: false

  - name: grafana-admin-password
    type: generic
    data:
      admin-password: "dev-grafana-admin-123"
    encrypted: false

  - name: database-credentials
    type: generic
    data:
      username: "dev-db-user"
      password: "dev-db-password-123"
      host: "localhost"
      port: "5432"
      database: "agentic_dev"
    encrypted: false

  - name: oauth2-credentials
    type: generic
    data:
      client-id: "dev-oauth2-client-id"
      client-secret: "dev-oauth2-client-secret"
      redirect-uri: "http://localhost:8080/oauth2/callback"
    encrypted: false

  - name: tls-certificates
    type: tls
    data:
      tls.crt: |
        -----BEGIN CERTIFICATE-----
        # Development self-signed certificate
        # This is a placeholder for development
        -----END CERTIFICATE-----
      tls.key: |
        -----BEGIN PRIVATE KEY-----
        # Development private key
        # This is a placeholder for development
        -----END PRIVATE KEY-----
    encrypted: false

  - name: docker-registry-credentials
    type: docker-registry
    data:
      .dockerconfigjson: |
        {
          "auths": {
            "gcr.io": {
              "username": "_json_key",
              "password": "dev-service-account-key",
              "email": "dev@example.com",
              "auth": "base64-encoded-credentials"
            }
          }
        }
    encrypted: false