# Production Environment Secrets
# IMPORTANT: All secrets must be encrypted and managed through secure channels
# This file should never contain actual production secrets in plain text

secrets:
  - name: gemini-api-key
    type: generic
    data:
      api-key: "PRODUCTION_GEMINI_API_KEY_ENCRYPTED_PLACEHOLDER"
    encrypted: true

  - name: redis-password
    type: generic
    data:
      password: "PRODUCTION_REDIS_PASSWORD_ENCRYPTED_PLACEHOLDER"
    encrypted: true

  - name: mcp-service-tokens
    type: generic
    data:
      user-service-token: "PRODUCTION_USER_SERVICE_TOKEN_ENCRYPTED_PLACEHOLDER"
      transaction-service-token: "PRODUCTION_TRANSACTION_SERVICE_TOKEN_ENCRYPTED_PLACEHOLDER"
      product-service-token: "PRODUCTION_PRODUCT_SERVICE_TOKEN_ENCRYPTED_PLACEHOLDER"
      order-service-token: "PRODUCTION_ORDER_SERVICE_TOKEN_ENCRYPTED_PLACEHOLDER"
    encrypted: true

  - name: a2a-encryption-keys
    type: generic
    data:
      encryption-key: "PRODUCTION_A2A_ENCRYPTION_KEY_ENCRYPTED_PLACEHOLDER"
      signing-key: "PRODUCTION_A2A_SIGNING_KEY_ENCRYPTED_PLACEHOLDER"
    encrypted: true

  - name: grafana-admin-password
    type: generic
    data:
      admin-password: "PRODUCTION_GRAFANA_ADMIN_PASSWORD_ENCRYPTED_PLACEHOLDER"
    encrypted: true

  - name: database-credentials
    type: generic
    data:
      username: "PRODUCTION_DB_USERNAME_ENCRYPTED_PLACEHOLDER"
      password: "PRODUCTION_DB_PASSWORD_ENCRYPTED_PLACEHOLDER"
      host: "production-db-host"
      port: "5432"
      database: "agentic_production"
    encrypted: true

  - name: oauth2-credentials
    type: generic
    data:
      client-id: "PRODUCTION_OAUTH2_CLIENT_ID_ENCRYPTED_PLACEHOLDER"
      client-secret: "PRODUCTION_OAUTH2_CLIENT_SECRET_ENCRYPTED_PLACEHOLDER"
      redirect-uri: "https://agentic-microservices.com/oauth2/callback"
    encrypted: true

  - name: tls-certificates
    type: tls
    data:
      tls.crt: "PRODUCTION_TLS_CERTIFICATE_ENCRYPTED_PLACEHOLDER"
      tls.key: "PRODUCTION_TLS_PRIVATE_KEY_ENCRYPTED_PLACEHOLDER"
    encrypted: true

  - name: docker-registry-credentials
    type: docker-registry
    data:
      .dockerconfigjson: "PRODUCTION_DOCKER_CONFIG_JSON_ENCRYPTED_PLACEHOLDER"
    encrypted: true

  - name: backup-credentials
    type: generic
    data:
      access-key-id: "PRODUCTION_BACKUP_ACCESS_KEY_ENCRYPTED_PLACEHOLDER"
      secret-access-key: "PRODUCTION_BACKUP_SECRET_KEY_ENCRYPTED_PLACEHOLDER"
      bucket-name: "agentic-production-backups"
      region: "us-central1"
    encrypted: true

  - name: monitoring-credentials
    type: generic
    data:
      prometheus-password: "PRODUCTION_PROMETHEUS_PASSWORD_ENCRYPTED_PLACEHOLDER"
      jaeger-password: "PRODUCTION_JAEGER_PASSWORD_ENCRYPTED_PLACEHOLDER"
    encrypted: true

  - name: disaster-recovery-credentials
    type: generic
    data:
      dr-access-key-id: "PRODUCTION_DR_ACCESS_KEY_ENCRYPTED_PLACEHOLDER"
      dr-secret-access-key: "PRODUCTION_DR_SECRET_KEY_ENCRYPTED_PLACEHOLDER"
      dr-bucket-name: "agentic-production-dr"
      dr-region: "us-east1"
    encrypted: true

  - name: compliance-audit-credentials
    type: generic
    data:
      audit-access-key: "PRODUCTION_AUDIT_ACCESS_KEY_ENCRYPTED_PLACEHOLDER"
      audit-secret-key: "PRODUCTION_AUDIT_SECRET_KEY_ENCRYPTED_PLACEHOLDER"
      audit-bucket: "agentic-production-audit-logs"
    encrypted: true

  - name: external-service-credentials
    type: generic
    data:
      payment-gateway-api-key: "PRODUCTION_PAYMENT_GATEWAY_API_KEY_ENCRYPTED_PLACEHOLDER"
      notification-service-token: "PRODUCTION_NOTIFICATION_SERVICE_TOKEN_ENCRYPTED_PLACEHOLDER"
      analytics-service-key: "PRODUCTION_ANALYTICS_SERVICE_KEY_ENCRYPTED_PLACEHOLDER"
    encrypted: true