# Staging Environment Secrets
# Note: These should be properly encrypted and managed in production

secrets:
  - name: gemini-api-key
    type: generic
    data:
      api-key: "STAGING_GEMINI_API_KEY_PLACEHOLDER"
    encrypted: true

  - name: redis-password
    type: generic
    data:
      password: "STAGING_REDIS_PASSWORD_PLACEHOLDER"
    encrypted: true

  - name: mcp-service-tokens
    type: generic
    data:
      user-service-token: "STAGING_USER_SERVICE_TOKEN_PLACEHOLDER"
      transaction-service-token: "STAGING_TRANSACTION_SERVICE_TOKEN_PLACEHOLDER"
      product-service-token: "STAGING_PRODUCT_SERVICE_TOKEN_PLACEHOLDER"
      order-service-token: "STAGING_ORDER_SERVICE_TOKEN_PLACEHOLDER"
    encrypted: true

  - name: a2a-encryption-keys
    type: generic
    data:
      encryption-key: "STAGING_A2A_ENCRYPTION_KEY_PLACEHOLDER"
      signing-key: "STAGING_A2A_SIGNING_KEY_PLACEHOLDER"
    encrypted: true

  - name: grafana-admin-password
    type: generic
    data:
      admin-password: "STAGING_GRAFANA_ADMIN_PASSWORD_PLACEHOLDER"
    encrypted: true

  - name: database-credentials
    type: generic
    data:
      username: "STAGING_DB_USERNAME_PLACEHOLDER"
      password: "STAGING_DB_PASSWORD_PLACEHOLDER"
      host: "staging-db-host"
      port: "5432"
      database: "agentic_staging"
    encrypted: true

  - name: oauth2-credentials
    type: generic
    data:
      client-id: "STAGING_OAUTH2_CLIENT_ID_PLACEHOLDER"
      client-secret: "STAGING_OAUTH2_CLIENT_SECRET_PLACEHOLDER"
      redirect-uri: "https://staging.agentic-microservices.com/oauth2/callback"
    encrypted: true

  - name: tls-certificates
    type: tls
    data:
      tls.crt: "STAGING_TLS_CERTIFICATE_PLACEHOLDER"
      tls.key: "STAGING_TLS_PRIVATE_KEY_PLACEHOLDER"
    encrypted: true

  - name: docker-registry-credentials
    type: docker-registry
    data:
      .dockerconfigjson: "STAGING_DOCKER_CONFIG_JSON_PLACEHOLDER"
    encrypted: true

  - name: backup-credentials
    type: generic
    data:
      access-key-id: "STAGING_BACKUP_ACCESS_KEY_PLACEHOLDER"
      secret-access-key: "STAGING_BACKUP_SECRET_KEY_PLACEHOLDER"
      bucket-name: "agentic-staging-backups"
      region: "us-central1"
    encrypted: true

  - name: monitoring-credentials
    type: generic
    data:
      prometheus-password: "STAGING_PROMETHEUS_PASSWORD_PLACEHOLDER"
      jaeger-password: "STAGING_JAEGER_PASSWORD_PLACEHOLDER"
    encrypted: true