apiVersion: v1
kind: ConfigMap
metadata:
  name: ai-agents-config
  namespace: ai-agents
  labels:
    app.kubernetes.io/name: agentic-microservices
    app.kubernetes.io/component: ai-agents
data:
  # A2A Communication Hub Configuration
  A2A_HUB_URL: "http://a2a-hub.integration.svc.cluster.local:8080"
  A2A_HUB_TIMEOUT: "30s"
  A2A_RETRY_ATTEMPTS: "3"
  A2A_RETRY_DELAY: "1s"
  
  # MCP Gateway Configuration
  MCP_GATEWAY_URL: "http://mcp-gateway.integration.svc.cluster.local:8080"
  MCP_TIMEOUT: "30s"
  MCP_RETRY_ATTEMPTS: "3"
  
  # Gemini AI Configuration
  GEMINI_API_ENDPOINT: "https://generativelanguage.googleapis.com"
  GEMINI_MODEL: "gemini-1.5-flash"
  GEMINI_TIMEOUT: "60s"
  GEMINI_MAX_TOKENS: "8192"
  
  # Logging Configuration
  LOG_LEVEL: "info"
  LOG_FORMAT: "json"
  
  # Monitoring Configuration
  METRICS_PORT: "9090"
  HEALTH_CHECK_PORT: "8080"
  HEALTH_CHECK_PATH: "/health"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: integration-config
  namespace: integration
  labels:
    app.kubernetes.io/name: agentic-microservices
    app.kubernetes.io/component: integration
data:
  # MCP Gateway Configuration
  MCP_PORT: "8080"
  MCP_RATE_LIMIT: "100"
  MCP_CIRCUIT_BREAKER_THRESHOLD: "5"
  MCP_CIRCUIT_BREAKER_TIMEOUT: "30s"
  
  # A2A Hub Configuration
  A2A_PORT: "8080"
  A2A_MESSAGE_RETENTION: "24h"
  A2A_MAX_MESSAGE_SIZE: "1MB"
  
  # Redis Configuration (for A2A message persistence)
  REDIS_HOST: "redis.integration.svc.cluster.local"
  REDIS_PORT: "6379"
  REDIS_DB: "0"
  
  # Logging Configuration
  LOG_LEVEL: "info"
  LOG_FORMAT: "json"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: infrastructure-config
  namespace: infrastructure
  labels:
    app.kubernetes.io/name: agentic-microservices
    app.kubernetes.io/component: infrastructure
data:
  # Monitoring Configuration
  PROMETHEUS_PORT: "9090"
  GRAFANA_PORT: "3000"
  
  # ADK Configuration
  ADK_PORT: "8080"
  ADK_TEMPLATES_PATH: "/app/templates"
  
  # Logging Configuration
  LOG_LEVEL: "info"
  LOG_FORMAT: "json"