apiVersion: v1
kind: ServiceAccount
metadata:
  name: ai-agent-service-account
  namespace: ai-agents
  labels:
    app.kubernetes.io/name: agentic-microservices
    app.kubernetes.io/component: ai-agents
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: integration-service-account
  namespace: integration
  labels:
    app.kubernetes.io/name: agentic-microservices
    app.kubernetes.io/component: integration
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: infrastructure-service-account
  namespace: infrastructure
  labels:
    app.kubernetes.io/name: agentic-microservices
    app.kubernetes.io/component: infrastructure
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: ai-agent-cluster-role
  labels:
    app.kubernetes.io/name: agentic-microservices
rules:
- apiGroups: [""]
  resources: ["pods", "services", "endpoints"]
  verbs: ["get", "list", "watch"]
- apiGroups: ["apps"]
  resources: ["deployments", "replicasets"]
  verbs: ["get", "list", "watch"]
- apiGroups: ["networking.k8s.io"]
  resources: ["ingresses"]
  verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: ai-agent-cluster-role-binding
  labels:
    app.kubernetes.io/name: agentic-microservices
subjects:
- kind: ServiceAccount
  name: ai-agent-service-account
  namespace: ai-agents
- kind: ServiceAccount
  name: integration-service-account
  namespace: integration
- kind: ServiceAccount
  name: infrastructure-service-account
  namespace: infrastructure
roleRef:
  kind: ClusterRole
  name: ai-agent-cluster-role
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: ai-agent-role
  namespace: ai-agents
  labels:
    app.kubernetes.io/name: agentic-microservices
rules:
- apiGroups: [""]
  resources: ["configmaps", "secrets"]
  verbs: ["get", "list", "watch"]
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: ai-agent-role-binding
  namespace: ai-agents
  labels:
    app.kubernetes.io/name: agentic-microservices
subjects:
- kind: ServiceAccount
  name: ai-agent-service-account
  namespace: ai-agents
roleRef:
  kind: Role
  name: ai-agent-role
  apiGroup: rbac.authorization.k8s.io